# Generated by Django 5.1.7 on 2025-10-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accountantprofile_accountant_and_more'),
        ('finance', '0002_alter_studentfeerecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
