# Generated by Django 5.1.7 on 2025-10-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_studentfeerecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
