# Generated by Django 5.1.7 on 2025-10-13 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_classroom_options_remove_classroom_level_and_more'),
        ('finance', '0004_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st', '1st Term'), ('2nd', '2nd Term'), ('3rd', '3rd Term')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feetype')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.session')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classroom')),
            ],
        ),
    ]
