# Generated by Django 5.1.7 on 2025-10-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_classroom_options_remove_classroom_level_and_more'),
        ('accounts', '0005_classroom'),
        ('finance', '0005_bulkfeeassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfeerecord',
            options={'ordering': ['-date_created'], 'verbose_name': 'Student Fee Record', 'verbose_name_plural': 'Student Fee Records'},
        ),
        migrations.AlterUniqueTogether(
            name='studentfeerecord',
            unique_together={('student', 'fee_type', 'session', 'term')},
        ),
    ]
