# Generated by Django 5.1.7 on 2025-10-07 08:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountantProfile',
            new_name='Accountant',
        ),
        migrations.RenameModel(
            old_name='AdminProfile',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='TeacherProfile',
            new_name='Teacher',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='Student',
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(default='profiles/default.png', upload_to='profiles/')),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], default='Guardian', max_length=20)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='accounts.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
    ]
