# Generated by Django 5.1.7 on 2025-10-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_classroom_alter_student_current_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
