# Generated by Django 5.1.7 on 2025-10-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_parent_children_remove_student_promoted_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='accounts.student'),
        ),
    ]
