# Generated by Django 5.1.7 on 2025-11-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_student_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassRoom',
        ),
    ]
