# Generated by Django 5.1.7 on 2025-11-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='date_of_birth',
        ),
    ]
