# Generated by Django 5.1.7 on 2025-10-08 07:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_result_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='Student',
        ),
    ]
