# Generated by Django 5.1.7 on 2025-10-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_attendancerecord_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='level',
        ),
        migrations.AddField(
            model_name='classroom',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
