# Generated by Django 5.1.7 on 2025-10-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
