# Generated by Django 5.1.7 on 2025-11-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_session_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='AttendanceSession',
        ),
    ]
