# Generated by Django 5.1.7 on 2025-11-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['student__user__username']},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-date', 'classroom__name', 'subject__name']},
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
